### ISSUE TITLE
Aligining of the navbar buttons

### ISSUE THREAD

**Issue by kamalbuilds** [legendarykamal/Lets-go-shop#1]
These three buttons should be of material ui and aligned horizontally.

![image](https://user-images.githubusercontent.com/95926324/184964042-53a98d38-1ca2-456f-b2af-a00bda372ffb.png)

**Comment by irfen-mi** [comment]
hello @legendarykamal assign me this to finish it.

**Comment by kamalbuilds** [comment]
thankyou for showing interest @developer-irfan , Yes sure go ahead !
