### ISSUE TITLE
Replacement of icons on Cart page with material UI icons

### ISSUE THREAD

**Issue by kamalbuilds** [legendarykamal/Lets-go-shop#11]
left, right and cross

![Screenshot from 2022-08-18 09-12-37](https://user-images.githubusercontent.com/95926324/185289061-0ef35dac-24e9-47ea-86a1-1604c1c9a7d6.png)

**Comment by ItzNesbroDev** [comment]
I will do it

**Comment by kamalbuilds** [comment]
great you showed interest , yes sure go ahead !

**Comment by kirtanchandak** [comment]
Hey can I work on this issue ?

**Comment by kamalbuilds** [comment]
Hey @kirtanchandak this has already been completed, check the site. 

But I encourage you to pick another one like this https://github.com/legendarykamal/Lets-go-shop/issues/7 Or another. 🙂
