### ISSUE TITLE
Delete automatically on Carts page 

### ISSUE THREAD

**Issue by kamalbuilds** [legendarykamal/Lets-go-shop#19]
#### Description

Delete automatically on Carts page when user decreases qty to zero as shown in ss below.

![Screenshot from 2022-08-19 20-57-32](https://user-images.githubusercontent.com/95926324/185654096-0b7a2988-352d-46be-b898-d7782c14370d.png)

#### Environment:
- Host OS: 
- Browser:

**Comment by WattBowers** [comment]
Hi there, would you mind if I took a crack at this?

**Comment by kamalbuilds** [comment]
@WattBowers All yours :+1:  All the info about setting up can be found in the README.md file . 
Star the repo if you like :wink:
