### ISSUE TITLE
Replace cart icon with material ui 

### ISSUE THREAD

**Issue by kamalbuilds** [legendarykamal/Lets-go-shop#2]
Desired output
![image](https://user-images.githubusercontent.com/95926324/185043267-cb226524-d67b-4154-9bb8-5ece2d62a851.png)

**Comment by Omafovbe** [comment]
Hi would love to work on this issue

**Comment by kamalbuilds** [comment]
hey @Omafovbe this issue has been already partially solved in #1 ,

Thank you for showing interest there will be plenty much issues to take up so look for them :smile:

**Comment by Omafovbe** [comment]
Thanks for the reply.
