### ISSUE TITLE
Enhancements for Add to cart button

### ISSUE THREAD

**Issue by tamalCodes** [legendarykamal/Lets-go-shop#31]
## Description
The `Add to cart` is bit off-place, and it looks bad !

## Expected Behavior
If you take a proper look, the add to cart is bit off-place, specially for mobiles ! 
Also, such a large button is **not a good UI**, for smaller screens.

I can fix it, and also replace the gray button with `a minimal cart icon` which will look much clean !

#### Image 1
![image](https://user-images.githubusercontent.com/72851613/186433487-75cdc3a4-f183-48e2-bd8f-d4127ff421e6.png)

## Environment:
- Host OS:  Windows 10
- Browser: Brave Browser

**Comment by kamalbuilds** [comment]
while this was on purpose but your idea too sounds great,  
you can start working on it @IAmTamal

**Comment by tamalCodes** [comment]
Cool ! 
I will make the changes then 🚀

**Comment by kamalbuilds** [comment]
@IAmTamal do update your PR with the latest changes .
