### ISSUE TITLE
changing the top banner image 

### ISSUE THREAD

**Issue by kamalbuilds** [legendarykamal/Lets-go-shop#7]
It is not as per the theme of the project .

**Comment by kirtanchandak** [comment]
can I work on this issue ?

**Comment by kamalbuilds** [comment]
Sure @kirtanchandak go ahead ⏩

**Comment by kirtanchandak** [comment]
What type of cover image do you prefer ?
![cover 2 test](https://user-images.githubusercontent.com/92196705/188592899-e4559278-dfcc-40cc-8a1e-d166a42a7657.png)
![cover 1 test](https://user-images.githubusercontent.com/92196705/188592911-0a0ba29c-5025-4413-ba0d-e486d8161662.png)

**Comment by kamalbuilds** [comment]
2 nd one looks better 🙂
