### ISSUE TITLE
changing the size of book 

### ISSUE THREAD

**Issue by kamalbuilds** [legendarykamal/Lets-go-shop#8]
![image](https://user-images.githubusercontent.com/95926324/185221856-f3cf1a12-8048-4447-88ce-9aac4d179dd6.png)

The size is quite huge -> align it to smaller + all the books to same size

**Comment by aigerimmmm** [comment]
Hey @legendarykamal can I work on this issue?

**Comment by kamalbuilds** [comment]
sounds nice, go ahead @aigerimmmm 
how to start is mentioned in the readme , good luck :+1:
