### ISSUE TITLE
Alignment of the icons

### ISSUE THREAD

**Issue by kamalbuilds** [legendarykamal/Lets-go-shop#9]
![image](https://user-images.githubusercontent.com/95926324/185288504-d8c7ae45-08fd-4bcd-b7c0-807445b73fd8.png)

The book and the cross icons are not aligned vertically.

**Comment by karancoder** [comment]
Hey @legendarykamal I have worked on fix. Please review it: https://github.com/legendarykamal/Lets-go-shop/pull/13

**Comment by kamalbuilds** [comment]
@karancoder  done reviewing :smiley:  , congratulations on being amongst the most earliest contributors :confetti_ball:

**Comment by karancoder** [comment]
Thanks, in case there are more bugs/features that I can help with, would be really happy to help!
